Added XDG support
haskell/haskeline pull request #157
Opened 2021-04-21 16:47 UTC by czaplicki

solving issue #150 

renamed readPrefsFromHome -> readUserPrefs
made readUserPrefs look for $XDG_CONFIG_HOME, check if it exists
and if so, readPrefs from it instead of $HOME/.haskeline.
If it doesen't exist, readPref from $HOME/.haskeline.

2021-05-03 23:45 UTC, MrQubo requested changes

2021-05-03 23:45 UTC, MrQubo commented on System/Console/Haskeline/InputT.hs
> +    xdg    <- getXdgDirectory XdgConfig ("haskline/haskeline")
This should be `"haskeline/haskeline"`, not `"haskline/haskeline"`.

2021-05-11 10:39 UTC, czaplicki commented on System/Console/Haskeline/InputT.hs
> +    xdg    <- getXdgDirectory XdgConfig ("haskline/haskeline")
Thanks, dyslectic with no autocomplete, so that slipped right passed me  :,o

2021-05-11 11:32 UTC, MrQubo approved these changes

2023-10-30 12:39 UTC, Lubsch commented
Sorry for basically just +1-ing this, but what has been blocking this from getting merged? I would really appreciate this feature.

2024-08-26 19:54 UTC, yzhou216 commented
Is there any update on this?

2025-02-04 16:51 UTC, qguv commented
This is one of the few remaining tools that doesn't support `XDG_CONFIG_HOME`. Any chance this approved PR can be merged soon?

2025-02-04 16:53 UTC, qguv commented
@athas, I see you [volunteered](https://github.com/haskell/haskeline/issues/185#issuecomment-2124200243) to maintain this package once it was moved to the `haskell` org, perhaps you could press the green button for us? 😄

2025-02-04 17:17 UTC, athas commented
I would, but I am not a maintainer. I am still willing to serve in that role if some GitHub Sultan is able to grant me the role.

2025-02-04 22:54 UTC, jokesper commented
I think @bgamari should have maintainer rights, since he merged the last commit into master.

2025-02-05 02:03 UTC, MrQubo commented
This PR should also update README.
https://github.com/haskell/haskeline/blob/073eca6df377c1d9593eb7bb2db10f152b05e2a6/README.md?plain=1#L21.

Wiki needs to be updated as well, but I don't think GitHub allows adding wiki changes as part of PR?

2025-02-05 22:07 UTC, bgamari commented
In principle I would welcome @athas helping with maintenance. Unfortunately, I don't actually have the permissions to make this happen myself. @Bodigrim, perhaps you could help here?

2025-02-05 22:40 UTC, Bodigrim commented
@athas give it a try now?

@bgamari could you please add https://hackage.haskell.org/user/TroelsHenriksen to https://hackage.haskell.org/package/haskeline/maintainers/edit ?

2025-02-05 23:50 UTC, bgamari commented
> @athas give it a try now?
> 
> @bgamari could you please add https://hackage.haskell.org/user/TroelsHenriksen to https://hackage.haskell.org/package/haskeline/maintainers/edit ?

Done.

2025-02-06 08:38 UTC, merged

2025-02-06 08:38 UTC, athas commented
I will take a few days to familiarise myself with haskeline (and update docs etc as necessary) before making a new release.

2025-02-06 09:02 UTC, qguv commented
Thanks a lot, everyone!!